create table breakfasts (id bigint generated by default as identity, price integer, room_id bigint, primary key (id))
create table cleanings (id bigint generated by default as identity, price integer, room_id bigint, primary key (id))
create table reserves (id bigint generated by default as identity, date date, room_id bigint, user_id bigint, primary key (id))
create table rooms (id bigint generated by default as identity, category varchar(255), number integer, price integer, primary key (id))
create table users (id bigint generated by default as identity, name varchar(255), password varchar(255), surname varchar(255), primary key (id))
alter table breakfasts add constraint FKop2nomxpr82sfytibjnsx291d foreign key (room_id) references rooms
alter table cleanings add constraint FK7e9qnkeftodpkucvc5asg49k4 foreign key (room_id) references rooms
alter table reserves add constraint FK26p77brpg6y6jfuls972byfk4 foreign key (room_id) references rooms
alter table reserves add constraint FKs2sbxomukajxrbd0f7080ysx4 foreign key (user_id) references users